### ISSUE TITLE
Missing README

### ISSUE THREAD

**Issue by jelly** [lahwaacz/archweb_manpages#3]
The project lacks a readme and installation instructions, which makes it hard to try it out locally.

**Comment by lahwaacz** [comment]
You're right that a readme would be useful, there is https://github.com/lahwaacz/archweb_manpages/issues/1 though.

**Comment by jelly** [comment]
Thanks, I totally missed that ticket!

**Comment by jelly** [comment]
Updated parts of #1 for #4
