### ISSUE TITLE
crash on mc(1)

### ISSUE THREAD

**Issue by nl6720** [lahwaacz/archweb_manpages#5]
http://jlk.fjfi.cvut.cz/arch/manpages/man/mc.1

```
500 — Internal server error
The web application crashed. 
```

**Comment by lahwaacz** [comment]
Thanks - fixed with a patched mandoc: http://jlk.fjfi.cvut.cz/git/aur/mandoc/commit/?id=eabff81be0d38b30878eea09bfa295b84bc0238b
