### ISSUE TITLE
netctl.profile(5): missing sections in TOC

### ISSUE THREAD

**Issue by nl6720** [lahwaacz/archweb_manpages#7]
[`netctl.profile(5)`](https://jlk.fjfi.cvut.cz/arch/manpages/man/netctl.profile.5) doesn't show the `OPTIONS FOR ... CONNECTIONS` sections in the table of contents.
The issue seems to be the fancy quoting used in the man page.

**Comment by lahwaacz** [comment]
Thanks for reporting!
