### ISSUE TITLE
Asynchronize manual page generation

### ISSUE THREAD

**Issue by FranklinYu** [lahwaacz/archweb_manpages#9]
When I first visit [less(1)](https://jlk.fjfi.cvut.cz/arch/manpages/man/less.1) today it wasn't responsive. Minutes later when I visit it again it becomes steadily available. I assume that it is only generated as needed. It would be cool if there is at least some response so that I won't be wondering whether the server is down.

**Comment by lahwaacz** [comment]
There was an unexpected downtime about 20-30 minutes ago.
